# Generated by Django 3.0.9 on 2020-08-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_observation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
