# Generated by Django 3.0.9 on 2020-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last activity'),
        ),
    ]
