# Generated by Django 3.0.9 on 2020-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mainuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is active'),
        ),
    ]
