# Generated by Django 3.0.9 on 2020-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200812_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
