# Generated by Django 3.0.9 on 2020-09-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200817_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='FCM Token'),
        ),
    ]
