# Generated by Django 3.0.9 on 2020-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mainuser_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='FCM Token'),
        ),
    ]
