# Generated by Django 3.0.9 on 2020-09-07 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200902_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1000, verbose_name='Identifier')),
                ('date', models.CharField(max_length=100, verbose_name='Date')),
                ('product_id', models.CharField(max_length=500, verbose_name='Product identifier')),
                ('time_amount', models.IntegerField(verbose_name='Time amount')),
                ('time_unit', models.PositiveSmallIntegerField(choices=[(1, 'Month'), (2, 'Year')], default=1, verbose_name='Time unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
