# Generated by Django 3.0.9 on 2020-09-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200930_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivation',
        ),
    ]
