# Generated by Django 3.0.9 on 2021-01-24 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_mainuser_show_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='followers',
            field=models.ManyToManyField(related_name='_mainuser_followers_+', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
    ]
