# Generated by Django 3.0.9 on 2021-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210124_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='in_recommendations',
            field=models.BooleanField(default=True, verbose_name='In recommendations'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Special'),
        ),
    ]
