# Generated by Django 3.0.9 on 2021-09-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_reaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='topic',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('goalster_ru', 'RU'), ('goalster_en', 'EN')], null=True, verbose_name='Firebase topic'),
        ),
    ]
