# Generated by Django 3.0.9 on 2021-09-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_mainuser_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='topic',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'RU'), ('2', 'EN')], null=True, verbose_name='Firebase topic'),
        ),
    ]
