# Generated by Django 3.0.9 on 2021-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210908_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='mainuser',
            name='is_celebrity',
            field=models.BooleanField(default=False, verbose_name='Celebrity'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
