# Generated by Django 3.0.9 on 2021-09-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210909_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Celebrity',
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.mainuser',),
        ),
    ]
