# Generated by Django 3.0.9 on 2021-09-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='my_order',
            new_name='order',
        ),
    ]
