# Generated by Django 3.0.9 on 2021-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20210920_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(default='Test', max_length=100, verbose_name='Название RU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Название EN'),
        ),
    ]
