# Generated by Django 3.0.9 on 2021-09-20 08:40

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20210920_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(upload_to=utils.upload.knowledge_image_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Image'),
        ),
    ]
