# Generated by Django 3.0.9 on 2021-09-20 10:54

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_section_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок EN')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок RU')),
                ('text_en', models.CharField(max_length=100, verbose_name='Текст EN')),
                ('text_ru', models.CharField(max_length=100, verbose_name='Текст RU')),
                ('image', models.ImageField(upload_to=utils.upload.knowledge_story_image_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Image')),
                ('link', models.URLField(verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='knowledge.Section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['order'],
            },
        ),
    ]
