# Generated by Django 3.0.9 on 2021-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text_en',
            field=models.TextField(verbose_name='Текст EN'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text_ru',
            field=models.TextField(verbose_name='Текст RU'),
        ),
    ]
