# Generated by Django 3.0.9 on 2021-09-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_auto_20210920_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title_ru',
        ),
    ]
