version: '3'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    expose:
    - 5673
    ports:
    - "5673:5672"
    volumes:
    - rabbit:/var/lib/rabbit
    - ./rabbit.conf:/etc/rabbit/rabbitmq.conf
    env_file:
    - ./.env.rabbit
    logging:
      driver: none
  celery:
    build: .
    command: celery -A goalster worker --pool=solo -l info
    depends_on:
    - db
    - rabbit
    env_file:
    - ./.env.test
  celery1:
    build: .
    command: celery -A goalster worker --pool=solo -l info
    depends_on:
    - db
    - rabbit
    env_file:
    - ./.env.test
  celery_beat:
    build: .
    command: celery -A goalster beat -l info
    depends_on:
    - db
    - rabbit
    env_file:
    - ./.env.test
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - "5433:5432"
    logging:
      driver: none
  web:
    build: .
    command: sh -c "/wait &&
      pip install -r requirements.txt &&
      python manage.py compilemessages --locale=ru &&
      python manage.py migrate &&
      python manage.py runserver 0:8000"
    volumes:
      - .:/goalster
      - test_data:/test_data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit
    links:
      - db
    env_file:
    - ./.env.test

volumes:
  postgres_data:
  rabbit:
  test_data: