# Generated by Django 3.0.9 on 2020-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedsphere',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration date'),
        ),
    ]
