# Generated by Django 3.0.9 on 2020-08-06 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200806_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='observer',
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Is confirmed')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observer', to='main.Goal', verbose_name='Goal')),
                ('observed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to=settings.AUTH_USER_MODEL, verbose_name='Observed')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed', to=settings.AUTH_USER_MODEL, verbose_name='Observer')),
            ],
        ),
    ]
