# Generated by Django 3.0.9 on 2020-08-06 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200806_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=utils.upload.visualization_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Image')),
                ('annotation', models.TextField(verbose_name='Annotation')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='main.SelectedSphere', verbose_name='Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
