# Generated by Django 3.0.9 on 2020-08-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200807_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='visualization',
            options={'verbose_name': 'Visualization', 'verbose_name_plural': 'Visualizations'},
        ),
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation date'),
        ),
    ]
