# Generated by Django 3.0.9 on 2020-08-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200807_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualization',
            old_name='goal',
            new_name='sphere',
        ),
    ]
