# Generated by Django 3.0.9 on 2020-08-07 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20200807_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='sphere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='main.SelectedSphere', verbose_name='Sphere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualization',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Annotation'),
        ),
    ]
