# Generated by Django 3.0.9 on 2020-08-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200807_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is confirmed'),
        ),
    ]
