# Generated by Django 3.0.9 on 2020-08-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_help'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='visualization',
            name='sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='main.SelectedSphere', verbose_name='Sphere'),
        ),
    ]
