# Generated by Django 3.0.9 on 2020-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200812_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedsphere',
            name='sphere',
            field=models.CharField(max_length=100, verbose_name='Sphere'),
        ),
        migrations.DeleteModel(
            name='Sphere',
        ),
    ]
