# Generated by Django 3.0.9 on 2020-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_question_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Question'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
