# Generated by Django 3.0.9 on 2020-08-20 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20200818_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observers', to=settings.AUTH_USER_MODEL, verbose_name='Observed'),
        ),
    ]
