# Generated by Django 3.0.9 on 2021-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_help_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is public'),
        ),
    ]
