# Generated by Django 3.0.9 on 2021-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210123_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_new_comment',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is new comment'),
        ),
    ]
