# Generated by Django 3.0.9 on 2021-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_goal_is_new_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is read'),
        ),
    ]
