# Generated by Django 3.0.9 on 2021-09-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_comment_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCustomizableNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(3, 'Об окончании периода'), (2, 'За 3 дня до окончания периода'), (4, 'Комментарий'), (5, 'Комментарий наблюдателю')], verbose_name='Type')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title EN')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Title RU')),
                ('body_en', models.TextField(null=True, verbose_name='Body EN')),
                ('body_ru', models.TextField(null=True, verbose_name='Body EN')),
            ],
            options={
                'verbose_name': 'Non customizable notification type',
                'verbose_name_plural': 'Non customizable notification types',
            },
        ),
    ]
