# Generated by Django 3.0.9 on 2021-09-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_noncustomizablenotificationtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonCustomizableNotificationType',
        ),
    ]
