# Generated by Django 3.0.9 on 2021-09-15 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0027_delete_celebrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('name', models.CharField(max_length=100, verbose_name='First name')),
                ('specialization', models.CharField(max_length=100, verbose_name='Specialization')),
                ('instagram_username', models.CharField(max_length=100, verbose_name='Instagram username')),
                ('avatar', models.FileField(upload_to=utils.upload.celebrity_avatar_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Celebrity',
                'verbose_name_plural': 'Celebrities',
            },
        ),
        migrations.CreateModel(
            name='CelebritySphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='celebrities.Celebrity', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Selected sphere',
                'verbose_name_plural': 'Selected spheres',
            },
        ),
        migrations.CreateModel(
            name='CelebrityReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_celebrity_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celebrity_reactions', to='users.ReactionType', verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reactions', to='celebrities.Celebrity', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
            },
        ),
        migrations.CreateModel(
            name='CelebrityGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('time', models.PositiveSmallIntegerField(choices=[(1, 'Morning'), (2, 'Day'), (3, 'Evening')], default=1, verbose_name='Time of the day')),
                ('sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='celebrities.CelebritySphere', verbose_name='Sphere')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='celebrities.Celebrity', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='CelebrityFollowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_celebrities', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='celebrities.Celebrity', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
            },
        ),
    ]
