# Generated by Django 3.0.9 on 2021-09-15 10:55

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_remove_celebritygoal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='specialization',
        ),
        migrations.CreateModel(
            name='CelebrityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First name')),
                ('specialization', models.CharField(max_length=100, verbose_name='Specialization')),
                ('instagram_username', models.CharField(max_length=100, verbose_name='Instagram username')),
                ('avatar', models.FileField(upload_to=utils.upload.celebrity_avatar_document_path, validators=[utils.validators.validate_file_size, utils.validators.basic_validate_images], verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='celebrities.Celebrity', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
