# Generated by Django 3.0.9 on 2021-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_auto_20210915_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebritygoal',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
