# Generated by Django 3.0.9 on 2021-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0008_auto_20210920_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebritygoal',
            options={'ordering': ['order'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='celebritysphere',
            options={'ordering': ['order'], 'verbose_name': 'Selected sphere', 'verbose_name_plural': 'Selected spheres'},
        ),
        migrations.AddField(
            model_name='celebritysphere',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='celebritygoal',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
