# Generated by Django 3.0.9 on 2021-09-07 09:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок EN')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок RU')),
                ('body_en', models.TextField(null=True, verbose_name='Тело EN')),
                ('body_ru', models.TextField(null=True, verbose_name='Тело EN')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), size=None, verbose_name='Weekdays')),
                ('time', models.PositiveSmallIntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Customizable notification type',
                'verbose_name_plural': 'Customizable notification types',
            },
        ),
    ]
