# Generated by Django 3.0.9 on 2021-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
        ('push_notifications', '0002_customizablenotificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposableNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок EN')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок RU')),
                ('body_en', models.TextField(null=True, verbose_name='Тело EN')),
                ('body_ru', models.TextField(null=True, verbose_name='Тело EN')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Disposable notification',
                'verbose_name_plural': 'Disposable notification',
            },
        ),
        migrations.CreateModel(
            name='PeriodicNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок EN')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок RU')),
                ('body_en', models.TextField(null=True, verbose_name='Тело EN')),
                ('body_ru', models.TextField(null=True, verbose_name='Тело EN')),
                ('time', models.TimeField(verbose_name='Time')),
                ('weekdays', models.ManyToManyField(related_name='notification_types', to='helper.Weekday', verbose_name='Weekday')),
            ],
            options={
                'verbose_name': 'Periodic notification',
                'verbose_name_plural': 'Periodic notifications',
            },
        ),
        migrations.DeleteModel(
            name='CustomizableNotificationType',
        ),
    ]
