# Generated by Django 3.0.9 on 2021-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_auto_20210907_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposablenotification',
            name='send_instantly',
            field=models.BooleanField(default=False, verbose_name='Send instantly'),
        ),
    ]
