# Generated by Django 3.0.9 on 2021-09-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0005_auto_20210907_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposablenotification',
            name='send_instantly',
            field=models.BooleanField(default=True, verbose_name='Send instantly'),
        ),
    ]
