# Generated by Django 3.0.9 on 2021-09-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0006_auto_20210907_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposablenotification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='disposablenotification',
            name='send_instantly',
        ),
        migrations.AlterField(
            model_name='noncustomizablenotificationtype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Об окончании периода'), (2, 'За 3 дня до окончания периода'), (4, 'Комментарий наставнику'), (5, 'Комментарий наблюдателю')], verbose_name='Type'),
        ),
    ]
