# Generated by Django 3.0.9 on 2021-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0008_auto_20210908_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposablenotification',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Тело EN'),
        ),
        migrations.AlterField(
            model_name='disposablenotification',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Тело EN'),
        ),
        migrations.AlterField(
            model_name='noncustomizablenotificationtype',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Тело EN'),
        ),
        migrations.AlterField(
            model_name='noncustomizablenotificationtype',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Тело EN'),
        ),
        migrations.AlterField(
            model_name='noncustomizablenotificationtype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Об окончании периода'), (2, 'За 3 дня до окончания периода'), (4, 'Комментарий наставнику'), (5, 'Комментарий наблюдателю'), (1, 'Если пользователь не заходит 3 дня'), (6, 'Оцени приложение'), (7, 'Для завершения целей')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='periodicnotification',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Тело EN'),
        ),
        migrations.AlterField(
            model_name='periodicnotification',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Тело EN'),
        ),
    ]
